import { state } from '../app/state.js';
import { parseNonTechBank } from '../interview/non-tech-bank.js';
import { createInterview } from '../api/client.js';

export function initializeLinkBaseUrlField() {
  const input = document.getElementById('linkBaseUrl');
  if (!input) return;
  input.disabled = true;
  input.placeholder = 'Generated by the backend on submit';
}

function showCopyButtonStatus(button, text, restoreAfterMs = 2000) {
  if (!button) return;
  const original = button.dataset.originalText || button.textContent;
  button.dataset.originalText = original;
  button.textContent = text;
  setTimeout(() => {
    button.textContent = button.dataset.originalText || original;
  }, restoreAfterMs);
}

function copySelectedInputValue(input) {
  input.focus();
  input.select();
  input.setSelectionRange(0, input.value.length);
  return document.execCommand && document.execCommand('copy');
}

export async function generateCandidateLink(event) {
  const name = document.getElementById('linkName').value.trim();
  const role = document.getElementById('linkRole').value.trim();
  const jd = document.getElementById('linkJd').value.trim();
  const resume = document.getElementById('linkResume').value.trim();

  if (!name || !role || !jd || !resume) {
    alert('Please fill in all four fields.');
    return;
  }
  if (!state.config.hrEmail) {
    alert('Please set the report recipient email in HR Configuration first.');
    return;
  }
  if (!state.config.nonTechBank) {
    alert('Please add the behavioral question bank in HR Configuration first.');
    return;
  }

  const behavioralBank = parseNonTechBank(state.config.nonTechBank);
  const linkInput = document.getElementById('generatedLink');
  const box = document.getElementById('generatedLinkBox');
  const info = document.getElementById('linkLengthInfo');
  const btn = event?.currentTarget;
  if (btn) btn.disabled = true;

  box.classList.remove('hidden');
  linkInput.value = '⏳ Creating session...';
  info.innerHTML = '<span class="text-gray-600">The backend is generating personalized questions. This usually takes 10-20 seconds — the candidate experience will be instant.</span>';

  try {
    const created = await createInterview({
      candidate_name: name,
      role_title: role,
      jd_text: jd,
      resume_text: resume,
      hr_email: state.config.hrEmail,
      include_intro: true,
      tech_count: state.config.techCount,
      behavioral_count: state.config.nonTechCount,
      pass_threshold: state.config.passThreshold,
      behavioral_bank: behavioralBank
    });

    linkInput.value = created.share_url;
    info.innerHTML = `<span class="text-green-800">✓ Link ready — expires ${new Date(created.expires_at).toLocaleString()}. Code: <code>${created.shortcode}</code>. The candidate will see a brief loading screen until the AI finishes priming.</span>`;
  } catch (e) {
    info.innerHTML = `<span class="text-red-700">✗ Failed to create session: ${e.message}</span>`;
    linkInput.value = '';
  } finally {
    if (btn) btn.disabled = false;
  }
}

export async function copyLink(event) {
  const inp = document.getElementById('generatedLink');
  const btn = event?.currentTarget;
  if (!inp || !inp.value) return;

  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(inp.value);
    } else if (!copySelectedInputValue(inp)) {
      throw new Error('Clipboard copy failed.');
    }
    showCopyButtonStatus(btn, '✓ Copied!');
  } catch {
    if (copySelectedInputValue(inp)) {
      showCopyButtonStatus(btn, '✓ Copied!');
    } else {
      showCopyButtonStatus(btn, 'Copy failed');
    }
  }
}
